const express=require('express')
const routes=express.Router()
const adminRoutes=require('../controllers/adminControllers')
const productRoutes=require('../controllers/productControllers')
const categoryRoutes=require('../controllers/categoryControllers')
const offerRoutes=require('../controllers/offerControllers')
const orderRoutes=require('../controllers/orderController')
const couponRoutes=require('../controllers/couponControllers')
const upload=require('../middlewares/upload')
const adminAuth=require('../middlewares/adminAuth')
const admin = require('../models/adminSchema')

routes.get('/', adminRoutes.loadAdminPage)
routes.post('/login', adminRoutes.adminAuthenticate)
routes.get('/dashboard', adminAuth, adminRoutes.showDashboard)
routes.get('/usersManagement', adminAuth, adminRoutes.showUserManagement)
routes.get('/userManagement/manageUser/:id', adminAuth, adminRoutes.manageUser)
routes.get('/categories', adminAuth, categoryRoutes.showCategories)
routes.get('/categories/addCategoryForm', adminAuth, categoryRoutes.addCategoriesForm)
routes.post('/categories/addCategory', adminAuth, categoryRoutes.addCategory)
routes.get('/categories/editCategory/:id', adminAuth, categoryRoutes.editCategoryForm)
routes.post('/categories/editCategory/submit/:id', adminAuth, categoryRoutes.editCategory)
routes.get('/categories/deleteCategory/:id', adminAuth, categoryRoutes.deleteCategory)
routes.get('/products', adminAuth, productRoutes.showProducts)
routes.get('/products/addProductForm', adminAuth, productRoutes.addProductForm)
routes.post('/products/addProduct', adminAuth, upload.array('productImages'), productRoutes.addProduct)
routes.get('/products/editProductForm/:id', adminAuth, productRoutes.editProductForm)
routes.post('/products/editProduct/:id', adminAuth, upload.array('productImages'), productRoutes.editProduct)
routes.get('/products/deleteProduct/:id', adminAuth, productRoutes.deleteProduct)
routes.get('/offers', adminAuth, offerRoutes.loadOfferPage)
routes.get('/offers/addOffer', adminAuth, offerRoutes.loadAddOfferPage)
routes.post('/offers/addOffer', adminAuth, offerRoutes.addOffer)
routes.get('/offers/editOffer/:id', adminAuth, offerRoutes.loadOfferEditPage)
routes.post('/offers/editOffer/:id', adminAuth, offerRoutes.editOffer)
routes.get('/offers/deleteOffer/:id', adminAuth, offerRoutes.deleteOffer)
routes.get('/orderManagement', adminAuth, orderRoutes.loadOrderManagement)
routes.get('/orderManagement/order-details/:order', adminAuth, orderRoutes.loadOrderDetails)
routes.get('/orderManagement/changeStatus/:status/:order', orderRoutes.updateStatus)
routes.post('/logout', adminRoutes.adminLogout)
routes.get('/coupons', adminAuth, couponRoutes.loadCoupons)
routes.get('/coupons/addCoupon', adminAuth, couponRoutes.loadCouponAddPage)
routes.post('/coupon/addCoupon', adminAuth, couponRoutes.addCoupon)
routes.get('/coupon/editCoupon/:id', adminAuth, couponRoutes.loadEditCouponPage)
routes.post('/coupon/editCoupon/:id', adminAuth, couponRoutes.editCoupon)
routes.get('/coupon/changeStatus/:id', adminAuth, couponRoutes.changeCouponStatus)
routes.get('/coupon/deleteCoupon/:id', adminAuth, couponRoutes.deleteCoupon)
routes.get('/order/confirmReturn', adminAuth, orderRoutes.confirmReturn)
routes.get('/getSalesReport', adminAuth, adminRoutes.getSalesReport)
routes.get('/downloadSalesReport', adminAuth, adminRoutes.downloadSalesReport)
routes.get('/downloadSalesExcelReport', adminAuth, adminRoutes.downloadSalesExcelReport)
routes.get('/addProductOffer', adminAuth, offerRoutes.addSingleProductOffer)
routes.get('/removeProductOffer', adminAuth, offerRoutes.removeSingleProductOffer)

module.exports=routes;