const express=require('express')
const routes=express.Router()
const userRoutes=require('../controllers/userControllers')
const productRoutes=require('../controllers/productControllers')
const addressRoutes=require('../controllers/addressControllers')
const orderRoutes=require('../controllers/orderController')
const cartRoutes=require('../controllers/cartController')
const passport=require('passport')
const userAuth=require('../middlewares/userAuth')
const blockCheck=require('../middlewares/blockedCheck')
const allowAuth=require('../middlewares/loginPageAuth')
const userContinue=require('../middlewares/userContinue')
const fetchAllow=require('../middlewares/fetchAllow')
const upload=require('../middlewares/upload')

routes.get('/', userRoutes.loadHomePage)
routes.get('/shop', blockCheck, productRoutes.loadShopPage)
routes.get('/shop/product-details/:id', blockCheck, productRoutes.loadProductDetailsPage)
routes.post('/shop/product-details/add-review/:id', userContinue, productRoutes.addProductReview)
routes.get('/login', allowAuth, blockCheck, userRoutes.loadLoginPage)
routes.get('/signup-Email', allowAuth, blockCheck, userRoutes.loadEmailSignupPage)
routes.post('/signup-SendOTP', userRoutes.sendOTP)
routes.post('/signup-VerifyOTP', userRoutes.verifyOTP)
routes.get('/changePassword', allowAuth, blockCheck, userAuth, userRoutes.loadChangePassword)
routes.post('/changePassword', userRoutes.changePassword)
routes.post('/resendOTP', userRoutes.resendOTP)
routes.get('/signup-details', allowAuth, blockCheck, userAuth, userRoutes.loadSignupPage)
routes.post('/signup-details', userRoutes.userSignup)
routes.post('/logout', userRoutes.userLogout)
routes.post('/login', userRoutes.userLogin)
routes.get('/forgot-password/emailverification', allowAuth, blockCheck, userRoutes.loadEmailVerificationPage)
routes.post('/signup-SendVerifyOTP', userRoutes.sendVerifyOTP)
routes.post('/recover-VerifyOTP', userRoutes.verifyRecoverOTP)
routes.get('/auth/google', allowAuth, passport.authenticate('google'))
routes.get('/auth/google/callback', allowAuth, passport.authenticate('google',{failureRedirect:'/user/login'}),(req,res)=>{
    req.session.userEmail=req.user.email
    req.session.isLogged = true
    res.redirect('/user')
})
routes.get('/settings/basicInfo', blockCheck, userContinue, userRoutes.loadBasicInfoPage)
routes.post('/settings/updateUser/:id', upload.single('userImage'), userRoutes.updateUser)
routes.get('/settings/manageAddress', blockCheck, userContinue, addressRoutes.manageAddress)
routes.get('/settings/addAddress', blockCheck, userContinue, addressRoutes.getAddAddressForm)
routes.post('/settings/addAddress', addressRoutes.addAddress)
routes.get('/settings/deleteAddress/:id', addressRoutes.deleteAddress)
routes.get('/settings/editAddress/:id', addressRoutes.getEditAddressForm)
routes.post('/settings/editAddress/:id', addressRoutes.editAddress)
routes.post('/settings/changePassword/:id', userRoutes.changePasswordFromSettings)
routes.post('/validatePassword', userRoutes.validatePassword)
routes.get('/settings/deleteUser/:id', userRoutes.deleteAccount)
routes.get('/cart', blockCheck, userContinue, cartRoutes.loadCartPage)
routes.get('/product/addToCart', fetchAllow, cartRoutes.addToCart)
routes.get('/cart/removeProduct', cartRoutes.removeProduct)
routes.get('/checkout/:cart', userContinue, orderRoutes.loadCheckoutPage)
routes.post('/settings/addAddressFromCheckout/:cart', addressRoutes.addAddressFromCheckout)
routes.get('/placeOrder', blockCheck, orderRoutes.placeOrder)
routes.get('/settings/orders', blockCheck, userContinue, orderRoutes.loadMyOrderPage)
routes.get('/order/order-summary/:order', orderRoutes.loadOrderSummary)
routes.get('/order/cancel-order/:order/:reason', orderRoutes.cancelOrder)

module.exports=routes